dev_report = \
['v9|ipas',
 'v9|psqi',
 'v9|pbi',
 'v9|pdq',
 'v9|ctq',
 'v9|staxi_2',
 'v9|followup',
 'v9|ssp',
 'v9|mfi_20',
 'v9|inout',
 'v9|meq_sa',
 'v9|mdq',
 'v9|cover',
 'v9|cover_other',
 'v9|les',
 'v9|pain',
 'v9|dsss',
 'v9|qids',
 'v9|hamd',
 'v9|ymrs',
 'v9|cgi',
 'v9|body_exam',
 'v9|demograph',
 'v9|psychosis',
 'v9|treatment',
 'v9|attacks',
 'v9|common_diease',
 'v9|somatopathy',
 'v9|longterm_diease',
 'v9|mense_pregnancy',
 'v9|abuse',
 'v9|family_history',
 'v9|hama',
 'v9|panns',
 'v9|moas',
 'v9|ybocs',
 'v9|gaf',
 'v9|tess',
 'v9|test_ekg',
 'v9|test_brs',
 'v9|test_bods',
 'v9|test_bfs',
 'v9|test_imms',
 'v9|test_drug',
 'v9|test_tm',
 'v9|test_hemodynamic',
 'v9|test_supersonic',
 'v9|test_bmd',
 'v9|test_ssep',
 'v9|test_baep',
 'v9|test_vep_pre',
 'v9|test_rep',
 'v9|test_cnv',
 'v9|test_emt',
 'v9|test_wm',
 'v9|test_wais_rc',
 'v9|test_wcst',
 'v9|sae']
 
self_report = \
['v0|cover',
 'v1|followup',
 'v1|pdq',
 'v2|followup',
 'v2|qids',
 'v2|dsss',
 'v2|pain',
 'v2|mfi_20',
 'v2|psqi',
 'v2|meq_sa',
 'v2|staxi_2',
 'v2|ipas',
 'v2|mdq',
 'v2|les',
 'v2|ssp',
 'v2|pbi',
 'v2|ctq',
 'v2|pdq',
 'v3|followup',
 'v3|dsss',
 'v3|mfi_20',
 'v3|pdq',
 'v4|followup',
 'v4|qids',
 'v4|dsss',
 'v4|pain',
 'v4|mfi_20',
 'v4|psqi',
 'v4|meq_sa',
 'v4|staxi_2',
 'v4|pdq',
 'v5|followup',
 'v5|qids',
 'v5|dsss',
 'v5|pain',
 'v5|mfi_20',
 'v5|psqi',
 'v5|meq_sa',
 'v5|staxi_2',
 'v5|pdq',
 'v6|followup',
 'v6|qids',
 'v6|dsss',
 'v6|pain',
 'v6|mfi_20',
 'v6|psqi',
 'v6|meq_sa',
 'v6|staxi_2',
 'v7|followup',
 'v7|qids',
 'v7|dsss',
 'v7|pain',
 'v7|mfi_20',
 'v7|psqi',
 'v7|meq_sa',
 'v7|staxi_2',
 'v8|followup',
 'v8|qids',
 'v8|dsss',
 'v8|pain',
 'v8|mfi_20',
 'v8|psqi',
 'v8|meq_sa',
 'v8|staxi_2']
 
other_report = \
 ['v0|cover_other',
 'v1|inout',
 'v1|hamd',
 'v1|ymrs',
 'v1|cgi',
 'v2|followup',
 'v2|body_exam',
 'v2|demograph',
 'v2|psychosis',
 'v2|treatment',
 'v2|attacks',
 'v2|common_diease',
 'v2|somatopathy',
 'v2|longterm_diease',
 'v2|mense_pregnancy',
 'v2|abuse',
 'v2|family_history',
 'v2|hamd',
 'v2|hama',
 'v2|ymrs',
 'v2|panns',
 'v2|moas',
 'v2|ybocs',
 'v2|cgi',
 'v2|gaf',
 'v2|tess',
 'v2|test_ekg',
 'v2|test_brs',
 'v2|test_bods',
 'v2|test_bfs',
 'v2|test_imms',
 'v2|test_drug',
 'v2|test_tm',
 'v2|test_hemodynamic',
 'v2|test_supersonic',
 'v2|test_bmd',
 'v2|test_ssep',
 'v2|test_baep',
 'v2|test_vep_pre',
 'v2|test_rep',
 'v2|test_cnv',
 'v2|test_emt',
 'v2|test_wm',
 'v2|test_wais_rc',
 'v2|test_wcst',
 'v3|followup',
 'v3|hamd',
 'v3|hama',
 'v3|ymrs',
 'v3|panns',
 'v3|moas',
 'v4|followup',
 'v4|hamd',
 'v4|hama',
 'v4|ymrs',
 'v4|panns',
 'v4|moas',
 'v4|ybocs',
 'v4|cgi',
 'v4|gaf',
 'v4|tess',
 'v4|test_drug',
 'v5|followup',
 'v5|body_exam',
 'v5|hamd',
 'v5|hama',
 'v5|ymrs',
 'v5|panns',
 'v5|moas',
 'v5|ybocs',
 'v5|cgi',
 'v5|gaf',
 'v5|tess',
 'v5|treatment',
 'v5|test_drug',
 'v6|followup',
 'v6|body_exam',
 'v6|mense_pregnancy',
 'v6|abuse',
 'v6|somatopathy',
 'v6|hamd',
 'v6|hama',
 'v6|ymrs',
 'v6|panns',
 'v6|moas',
 'v6|ybocs',
 'v6|cgi',
 'v6|gaf',
 'v6|tess',
 'v6|sae',
 'v6|treatment',
 'v6|test_ekg',
 'v6|test_brs',
 'v6|test_bods',
 'v6|test_bfs',
 'v6|test_imms',
 'v6|test_drug',
 'v7|followup',
 'v7|body_exam',
 'v7|hamd',
 'v7|hama',
 'v7|ymrs',
 'v7|panns',
 'v7|moas',
 'v7|ybocs',
 'v7|cgi',
 'v7|gaf',
 'v7|tess',
 'v7|treatment',
 'v8|followup',
 'v8|body_exam',
 'v8|mense_pregnancy',
 'v8|abuse',
 'v8|somatopathy',
 'v8|hamd',
 'v8|hama',
 'v8|ymrs',
 'v8|panns',
 'v8|moas',
 'v8|ybocs',
 'v8|cgi',
 'v8|gaf',
 'v8|tess',
 'v8|sae',
 'v8|treatment',
 'v8|test_ekg',
 'v8|test_brs',
 'v8|test_bods',
 'v8|test_hemodynamic',
 'v8|test_imms',
 'v8|test_drug']
 
self_nav = \
{'v0': [('cover', '封面')],
            'v1': [('followup', '随访'),
                   ('pdq', '抑郁症认知损害问卷')],
            'v2': [('followup', '随访'),
                   ('qids', '抑郁症状快速检查自我报告评分16项'),
                   ('dsss', '抑郁和躯体症状量表'),
                   ('pain', '疼痛问卷'),
                   ('mfi_20', '多维疲劳量表'),
                   ('psqi', '匹兹堡睡眠指数'),
                   ('meq_sa', '清晨型和夜晚型问卷'),
                   ('staxi_2', '状态-特质怒表单量表II'),
                   ('ipas', 'Impulsive/Premeditated Aggression Scale'),
                   ('mdq', '心境障碍问卷'),
                   ('les', '生活事件量表'),
                   ('ssp', '瑞士大学人格问卷'),
                   ('pbi', '父母教育方式'),
                   ('ctq', '儿童期虐待'),
                   ('pdq', '抑郁症认知损害问卷')],
            'v3': [('followup', '随访'),
                   ('dsss', '抑郁和躯体症状量表'),
                   ('mfi_20', '多维疲劳量表'),
                   ('pdq', '抑郁症认知损害问卷')],
            'v4': [('followup', '随访'),
                   ('qids', '抑郁症状快速检查自我报告评分16项'),
                   ('dsss', '抑郁和躯体症状量表'),
                   ('pain', '疼痛问卷'),
                   ('mfi_20', '多维疲劳量表'),
                   ('psqi', '匹兹堡睡眠指数'),
                   ('meq_sa', '清晨型和夜晚型问卷'),
                   ('staxi_2', '状态-特质怒表单量表II'),
                   ('pdq', '抑郁症认知损害问卷')],
            'v5': [('followup', '随访'),
                   ('qids', '抑郁症状快速检查自我报告评分16项'),
                   ('dsss', '抑郁和躯体症状量表'),
                   ('pain', '疼痛问卷'),
                   ('mfi_20', '多维疲劳量表'),
                   ('psqi', '匹兹堡睡眠指数'),
                   ('meq_sa', '清晨型和夜晚型问卷'),
                   ('staxi_2', '状态-特质怒表单量表II'),
                   ('pdq', '抑郁症认知损害问卷')],
            'v6': [('followup', '随访'),
                   ('qids', '抑郁症状快速检查自我报告评分16项'),
                   ('dsss', '抑郁和躯体症状量表'),
                   ('pain', '疼痛问卷'),
                   ('mfi_20', '多维疲劳量表'),
                   ('psqi', '匹兹堡睡眠指数'),
                   ('meq_sa', '清晨型和夜晚型问卷'),
                   ('staxi_2', '状态-特质怒表单量表II')],
            'v7': [('followup', '随访'),
                   ('qids', '抑郁症状快速检查自我报告评分16项'),
                   ('dsss', '抑郁和躯体症状量表'),
                   ('pain', '疼痛问卷'),
                   ('mfi_20', '多维疲劳量表'),
                   ('psqi', '匹兹堡睡眠指数'),
                   ('meq_sa', '清晨型和夜晚型问卷'),
                   ('staxi_2', '状态-特质怒表单量表II')],
            'v8': [('followup', '随访'),
                   ('qids', '抑郁症状快速检查自我报告评分16项'),
                   ('dsss', '抑郁和躯体症状量表'),
                   ('pain', '疼痛问卷'),
                   ('mfi_20', '多维疲劳量表'),
                   ('psqi', '匹兹堡睡眠指数'),
                   ('meq_sa', '清晨型和夜晚型问卷'),
                   ('staxi_2', '状态-特质怒表单量表II')]}
                   
other_nav = \
{'v0': [('cover_other', '封面')],
 'v1': [('inout', '筛选标准'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('cgi', '临床总体印象量表')],
 'v2': [('followup', '随访'),
        ('body_exam', '体格检查'),
        ('demograph', '人口学资料'),
        ('psychosis', '精神疾病史'),
        ('treatment', '治疗记录'),
        ('attacks', '本次发作情况'),
        ('common_diease', '共病'),
        ('somatopathy', '躯体疾病史'),
        ('longterm_diease', '长期治疗躯体疾病'),
        ('mense_pregnancy', '月经妊娠史'),
        ('abuse', '物质使用史'),
        ('family_history', '家族史'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('hama', '汉密顿焦虑量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('panns', '阳性及阴性症状量表'),
        ('moas', '修改版外显攻击行为量表'),
        ('ybocs', '耶鲁布朗强迫症严重程度标准量表'),
        ('cgi', '临床总体印象量表'),
        ('gaf', '功能大体评定量表量表'),
        ('tess', '副反应量表'),
        ('test_ekg', '心电图'),
        ('test_brs', '血常规'),
        ('test_bods', '生化'),
        ('test_bfs', '血液流变学'),
        ('test_imms', '免疫内分泌'),
        ('test_drug', '药物浓度记录表'),
        ('test_tm', '肿瘤标志物'),
        ('test_hemodynamic', '血流动力学'),
        ('test_supersonic', 'B超记录'),
        ('test_bmd', '骨密度'),
        ('test_ssep', '体感诱发电位检查'),
        ('test_baep', '脑干听觉反映报告'),
        ('test_vep_pre', '棋盘格翻转诱发电位检查'),
        ('test_rep', '认知诱发电位检查'),
        ('test_cnv', '关联性负变检查'),
        ('test_emt', '眼动测定分析'),
        ('test_wm', '韦氏记忆测验'),
        ('test_wais_rc', '韦氏智力检验记录表'),
        ('test_wcst', '威斯康星卡片分类检验')],
 'v3': [('followup', '随访'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('hama', '汉密顿焦虑量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('panns', '阳性及阴性症状量表'),
        ('moas', '修改版外显攻击行为量表')],
 'v4': [('followup', '随访'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('hama', '汉密顿焦虑量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('panns', '阳性及阴性症状量表'),
        ('moas', '修改版外显攻击行为量表'),
        ('ybocs', '耶鲁布朗强迫症严重程度标准量表'),
        ('cgi', '临床总体印象量表'),
        ('gaf', '功能大体评定量表量表'),
        ('tess', '副反应量表'),
        ('test_drug', '药物浓度记录表')],
 'v5': [('followup', '随访'),
        ('body_exam', '体格检查'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('hama', '汉密顿焦虑量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('panns', '阳性及阴性症状量表'),
        ('moas', '修改版外显攻击行为量表'),
        ('ybocs', '耶鲁布朗强迫症严重程度标准量表'),
        ('cgi', '临床总体印象量表'),
        ('gaf', '功能大体评定量表量表'),
        ('tess', '副反应量表'),
        ('treatment', '治疗记录'),
        ('test_drug', '药物浓度记录表')],
 'v6': [('followup', '随访'),
        ('body_exam', '体格检查'),
        ('mense_pregnancy', '月经妊娠史'),
        ('abuse', '物质使用史'),
        ('somatopathy', '躯体疾病史'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('hama', '汉密顿焦虑量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('panns', '阳性及阴性症状量表'),
        ('moas', '修改版外显攻击行为量表'),
        ('ybocs', '耶鲁布朗强迫症严重程度标准量表'),
        ('cgi', '临床总体印象量表'),
        ('gaf', '功能大体评定量表量表'),
        ('tess', '副反应量表'),
        ('sae', '严重不良事件报告'),
        ('treatment', '治疗记录'),
        ('test_ekg', '心电图'),
        ('test_brs', '血常规'),
        ('test_bods', '生化'),
        ('test_bfs', '血液流变学'),
        ('test_imms', '免疫内分泌'),
        ('test_drug', '药物浓度记录表')],
 'v7': [('followup', '随访'),
        ('body_exam', '体格检查'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('hama', '汉密顿焦虑量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('panns', '阳性及阴性症状量表'),
        ('moas', '修改版外显攻击行为量表'),
        ('ybocs', '耶鲁布朗强迫症严重程度标准量表'),
        ('cgi', '临床总体印象量表'),
        ('gaf', '功能大体评定量表量表'),
        ('tess', '副反应量表'),
        ('treatment', '治疗记录')],
 'v8': [('followup', '随访'),
        ('body_exam', '体格检查'),
        ('mense_pregnancy', '月经妊娠史'),
        ('abuse', '物质使用史'),
        ('somatopathy', '躯体疾病史'),
        ('hamd', '汉密尔顿抑郁量表'),
        ('hama', '汉密顿焦虑量表'),
        ('ymrs', '杨氏躁狂量表'),
        ('panns', '阳性及阴性症状量表'),
        ('moas', '修改版外显攻击行为量表'),
        ('ybocs', '耶鲁布朗强迫症严重程度标准量表'),
        ('cgi', '临床总体印象量表'),
        ('gaf', '功能大体评定量表量表'),
        ('tess', '副反应量表'),
        ('sae', '严重不良事件报告'),
        ('treatment', '治疗记录'),
        ('test_ekg', '心电图'),
        ('test_brs', '血常规'),
        ('test_bods', '生化'),
        ('test_hemodynamic', '血流动力学'),
        ('test_imms', '免疫内分泌'),
        ('test_drug', '药物浓度记录表')]}