# -*- coding: utf-8 -*-
import csv
from . import db
from .models import Patient

class Export:
    """helper class FOR export database as csv file"""
    __tablename__ = None
    export_cols = None
    
    @classmethod
    def export2csv(cls, csv_file=None):
        csv_file = cls.__tablename__ + '.csv' if csv_file is None else csv_file
        ints = cls.query.all()
        col_names = ['p_id', 'status']
        col_names += [cls.__tablename__ + col for col in cls.export_cols]
        with open(csv_file, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(col_names)
            for int in ints:
                line = [getattr(int, attr) for attr in cls.export_cols]
                writer.writerow(line)
    
class FOLLOWUP(db.Model):
    __tablename__ = 'follow_ups'
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    q_1 = db.Column(db.String(16))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(16))
    q_7 = db.Column(db.Integer)
    
    def __repr__(self):
        return '<FollowUP {}>'.format(self.status)
    
class QIDS(db.Model, Export):
    __tablename__ = 'qids_sr16'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    
    def __repr__(self):
        return '<QIDS {}>'.format(self.id)
        
class DSSS(db.Model, Export):
    __tablename__ = 'dsss'
    export_cols = ('p_id', 'status','q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21', 'q_22')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    
    def __repr__(self):
        return '<DSSS {}>'.format(self.id)
        
class PAIN(db.Model, Export):
    __tablename__ = 'pain'
    export_cols = ('p_id', 'status','q_1', 'q_2', 'q_3', 'q_4')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(16))
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    
    def __repr__(self):
        return '<PAIN {}>'.format(self.id)
 
class MFI(db.Model, Export):
    __tablename__ = 'mfi_20'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    
class PSQI(db.Model, Export):
    __tablename__ = 'psqi'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 
    'q_5_1', 'q_5_2', 'q_5_3', 'q_5_4', 'q_5_5', 'q_5_6', 'q_5_7', 'q_5_8', 'q_5_9', 'q_5_10',
    'q_6', 'q_7', 'q_8', 'q_9')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5_1 = db.Column(db.Integer)
    q_5_2 = db.Column(db.Integer)
    q_5_3 = db.Column(db.Integer)
    q_5_4 = db.Column(db.Integer)
    q_5_5 = db.Column(db.Integer)
    q_5_6 = db.Column(db.Integer)
    q_5_7 = db.Column(db.Integer)
    q_5_8 = db.Column(db.Integer)
    q_5_9 = db.Column(db.Integer)
    q_5_10 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    
class MEQ_SA(db.Model, Export):
    __tablename__ = 'meq_sa'
    export_cols = export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)

class STAXI_2(db.Model, Export):
    __tablename__ = 'staxi_2'
    export_cols = ('p_id', 'status','q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9',
    'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21',
    'q_22', 'q_23', 'q_24', 'q_25', 'q_26', 'q_27', 'q_28', 'q_29', 'q_30', 'q_31', 'q_32', 'q_33',
    'q_34', 'q_35', 'q_36', 'q_37', 'q_38', 'q_39', 'q_40', 'q_41', 'q_42', 'q_43', 'q_44', 'q_45',
    'q_46', 'q_47', 'q_48', 'q_49', 'q_50', 'q_51', 'q_52', 'q_53', 'q_54', 'q_55', 'q_56', 'q_57')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    q_23 = db.Column(db.Integer)
    q_24 = db.Column(db.Integer)
    q_25 = db.Column(db.Integer)
    q_26 = db.Column(db.Integer)
    q_27 = db.Column(db.Integer)
    q_28 = db.Column(db.Integer)
    q_29 = db.Column(db.Integer)
    q_30 = db.Column(db.Integer)
    q_31 = db.Column(db.Integer)
    q_32 = db.Column(db.Integer)
    q_33 = db.Column(db.Integer)
    q_34 = db.Column(db.Integer)
    q_35 = db.Column(db.Integer)
    q_36 = db.Column(db.Integer)
    q_37 = db.Column(db.Integer)
    q_38 = db.Column(db.Integer)
    q_39 = db.Column(db.Integer)
    q_40 = db.Column(db.Integer)
    q_41 = db.Column(db.Integer)
    q_42 = db.Column(db.Integer)
    q_43 = db.Column(db.Integer)
    q_44 = db.Column(db.Integer)
    q_45 = db.Column(db.Integer)
    q_46 = db.Column(db.Integer)
    q_47 = db.Column(db.Integer)
    q_48 = db.Column(db.Integer)
    q_49 = db.Column(db.Integer)
    q_50 = db.Column(db.Integer)
    q_51 = db.Column(db.Integer)
    q_52 = db.Column(db.Integer)
    q_53 = db.Column(db.Integer)
    q_54 = db.Column(db.Integer)
    q_55 = db.Column(db.Integer)
    q_56 = db.Column(db.Integer)
    q_57 = db.Column(db.Integer)
    
class IPAS(db.Model, Export):
    __tablename__ = 'ipas'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9',
    'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21',
    'q_23', 'q_24', 'q_25', 'q_26', 'q_27', 'q_28', 'q_29', 'q_30')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    q_23 = db.Column(db.Integer)
    q_24 = db.Column(db.Integer)
    q_25 = db.Column(db.Integer)
    q_26 = db.Column(db.Integer)
    q_27 = db.Column(db.Integer)
    q_28 = db.Column(db.Integer)
    q_29 = db.Column(db.Integer)
    q_30 = db.Column(db.Integer)
    
class MDQ(db.Model, Export):
    __tablename__ = 'mdq'
    export_cols = ('p_id', 'status', 'q_1_1', 'q_1_2', 'q_1_3', 'q_1_4', 'q_1_5', 'q_1_6', 'q_1_7',
    'q_1_8', 'q_1_9', 'q_1_10', 'q_1_11', 'q_1_12', 'q_1_13', 'q_2', 'q_3')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1_1 = db.Column(db.Integer)
    q_1_2 = db.Column(db.Integer)
    q_1_3 = db.Column(db.Integer)
    q_1_4 = db.Column(db.Integer)
    q_1_5 = db.Column(db.Integer)
    q_1_6 = db.Column(db.Integer)
    q_1_7 = db.Column(db.Integer)
    q_1_8 = db.Column(db.Integer)
    q_1_9 = db.Column(db.Integer)
    q_1_10 = db.Column(db.Integer)
    q_1_11 = db.Column(db.Integer)
    q_1_12 = db.Column(db.Integer)
    q_1_13 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    
class SSP(db.Model, Export):
    __tablename__ = 'ssp'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11',
    'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21', 'q_22',
    'q_23', 'q_24', 'q_25', 'q_26', 'q_27', 'q_28', 'q_29', 'q_30', 'q_31', 'q_32', 'q_33',
    'q_34', 'q_35', 'q_36', 'q_37', 'q_38', 'q_39', 'q_40', 'q_41', 'q_42', 'q_43', 'q_44',
    'q_45', 'q_46', 'q_47', 'q_48', 'q_49', 'q_50', 'q_51', 'q_52', 'q_53', 'q_54', 'q_55',
    'q_56', 'q_57', 'q_58', 'q_59', 'q_60', 'q_61', 'q_62', 'q_63', 'q_64', 'q_65', 'q_66',
    'q_67', 'q_68', 'q_69', 'q_70', 'q_71', 'q_72', 'q_73', 'q_74', 'q_75', 'q_76', 'q_77',
    'q_78', 'q_79', 'q_80', 'q_81', 'q_82', 'q_83', 'q_84', 'q_85', 'q_86', 'q_87', 'q_88',
    'q_89', 'q_90', 'q_91')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    q_23 = db.Column(db.Integer)
    q_24 = db.Column(db.Integer)
    q_25 = db.Column(db.Integer)
    q_26 = db.Column(db.Integer)
    q_27 = db.Column(db.Integer)
    q_28 = db.Column(db.Integer)
    q_29 = db.Column(db.Integer)
    q_30 = db.Column(db.Integer)
    q_31 = db.Column(db.Integer)
    q_32 = db.Column(db.Integer)
    q_33 = db.Column(db.Integer)
    q_34 = db.Column(db.Integer)
    q_35 = db.Column(db.Integer)
    q_36 = db.Column(db.Integer)
    q_37 = db.Column(db.Integer)
    q_38 = db.Column(db.Integer)
    q_39 = db.Column(db.Integer)
    q_40 = db.Column(db.Integer)
    q_41 = db.Column(db.Integer)
    q_42 = db.Column(db.Integer)
    q_43 = db.Column(db.Integer)
    q_44 = db.Column(db.Integer)
    q_45 = db.Column(db.Integer)
    q_46 = db.Column(db.Integer)
    q_47 = db.Column(db.Integer)
    q_48 = db.Column(db.Integer)
    q_49 = db.Column(db.Integer)
    q_50 = db.Column(db.Integer)
    q_51 = db.Column(db.Integer)
    q_52 = db.Column(db.Integer)
    q_53 = db.Column(db.Integer)
    q_54 = db.Column(db.Integer)
    q_55 = db.Column(db.Integer)
    q_56 = db.Column(db.Integer)
    q_57 = db.Column(db.Integer)
    q_58 = db.Column(db.Integer)
    q_59 = db.Column(db.Integer)
    q_60 = db.Column(db.Integer)
    q_61 = db.Column(db.Integer)
    q_62 = db.Column(db.Integer)
    q_63 = db.Column(db.Integer)
    q_64 = db.Column(db.Integer)
    q_65 = db.Column(db.Integer)
    q_66 = db.Column(db.Integer)
    q_67 = db.Column(db.Integer)
    q_68 = db.Column(db.Integer)
    q_69 = db.Column(db.Integer)
    q_70 = db.Column(db.Integer)
    q_71 = db.Column(db.Integer)
    q_72 = db.Column(db.Integer)
    q_73 = db.Column(db.Integer)
    q_74 = db.Column(db.Integer)
    q_75 = db.Column(db.Integer)
    q_76 = db.Column(db.Integer)
    q_77 = db.Column(db.Integer)
    q_78 = db.Column(db.Integer)
    q_79 = db.Column(db.Integer)
    q_80 = db.Column(db.Integer)
    q_81 = db.Column(db.Integer)
    q_82 = db.Column(db.Integer)
    q_83 = db.Column(db.Integer)
    q_84 = db.Column(db.Integer)
    q_85 = db.Column(db.Integer)
    q_86 = db.Column(db.Integer)
    q_87 = db.Column(db.Integer)
    q_88 = db.Column(db.Integer)
    q_89 = db.Column(db.Integer)
    q_90 = db.Column(db.Integer)
    q_91 = db.Column(db.Integer)
    
class PBI(db.Model, Export):
    __tablename__ = 'pbi'
    export_cols = ('p_id', 'status', 'parent', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8',
    'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20',
    'q_21', 'q_22', 'q_23', 'q_24', 'q_25')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    parent = db.Column(db.String(16))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    q_23 = db.Column(db.Integer)
    q_24 = db.Column(db.Integer)
    q_25 = db.Column(db.Integer)
    
class CTQ(db.Model, Export):
    __tablename__ = 'ctq'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11',
    'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21', 'q_22', 'q_23', 'q_24', 'q_25',
    'q_26', 'q_27', 'q_28')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    q_23 = db.Column(db.Integer)
    q_24 = db.Column(db.Integer)
    q_25 = db.Column(db.Integer)
    q_26 = db.Column(db.Integer)
    q_27 = db.Column(db.Integer)
    q_28 = db.Column(db.Integer)
    
class LES(db.Model, Export):
    __tablename__ = 'les'
    export_cols = ('p_id', 'status', 'event_code', 'event_date', 'property', 'degree', 'duration', 'note')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Text)

class INOUT(db.Model, Export):
    __tablename__ = 'inout'
    export_cols = ('p_id', 'status', 'q_1', 'q_2')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(16))
    q_2 = db.Column(db.String(16))
    
class HAMD(db.Model, Export):
    __tablename__ = 'hamd'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8',
    'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    
class YMRS(db.Model, Export):
    __tablename__ = 'ymrs'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9',
    'q_10', 'q_11')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    
class CGI(db.Model, Export):
    __tablename__ = 'cgi'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    
class BODY_EXAM(db.Model, Export):
    __tablename__ = 'body_exam'
    export_cols = ('p_id', 'status', 'q_1_1', 'q_1_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1_1 = db.Column(db.Float)
    q_1_2 = db.Column(db.Float)
    q_2 = db.Column(db.Float)
    q_3 = db.Column(db.Float)
    q_4 = db.Column(db.Float)
    q_5 = db.Column(db.Float)
    q_6 = db.Column(db.Float)
    q_7 = db.Column(db.Float)
 
class DEMOGRAPH(db.Model, Export):
    __tablename__ = 'demograph'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21', 'q_22', 'q_23', 'q_24')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.String(64))
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.String(64))
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.String(64))
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.String(64))
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    q_23 = db.Column(db.String(64))
    q_24 = db.Column(db.String(64))
    
class PSYCHOISI(db.Model, Export):
    __tablename__ = 'psychoisi'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21', 'q_22', 'q_23', 'q_24', 'q_25', 'q_26', 'q_27', 'q_28', 'q_29', 'q_30', 'q_31_1', 'q_31_2', 'q_31_3', 'q_32', 'q_33', 'q_34', 'q_35', 'q_36', 'q_37', 'q_38', 'q_39', 'q_40', 'q_41', 'q_42', 'q_43', 'q_44', 'q_45', 'q_46', 'q_47', 'q_48', 'q_49')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.String(64))
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.String(64))
    q_13 = db.Column(db.String(64))
    q_14 = db.Column(db.String(64))
    q_15 = db.Column(db.String(64))
    q_16 = db.Column(db.String(64))
    q_17 = db.Column(db.String(64))
    q_18 = db.Column(db.String(64))
    q_19 = db.Column(db.String(64))
    q_20 = db.Column(db.String(64))
    q_21 = db.Column(db.String(64))
    q_22 = db.Column(db.String(64))
    q_23 = db.Column(db.String(64))
    q_24 = db.Column(db.String(64))
    q_25 = db.Column(db.Integer)
    q_26 = db.Column(db.Integer)
    q_27 = db.Column(db.String(64))
    q_28 = db.Column(db.String(64))
    q_29 = db.Column(db.String(64))
    q_30 = db.Column(db.Integer)
    q_31_1 = db.Column(db.Integer)
    q_31_2 = db.Column(db.String(64))
    q_31_3 = db.Column(db.String(64))
    q_32 = db.Column(db.String(64))
    q_33 = db.Column(db.String(64))
    q_34 = db.Column(db.String(64))
    q_35 = db.Column(db.String(64))
    q_36 = db.Column(db.String(64))
    q_37 = db.Column(db.String(64))
    q_38 = db.Column(db.String(64))
    q_39 = db.Column(db.String(64))
    q_40 = db.Column(db.String(64))
    q_41 = db.Column(db.String(64))
    q_42 = db.Column(db.String(64))
    q_43 = db.Column(db.Integer)
    q_44 = db.Column(db.Integer)
    q_45 = db.Column(db.Integer)
    q_46 = db.Column(db.Integer)
    q_47 = db.Column(db.Integer)
    q_48 = db.Column(db.Integer)
    q_49 = db.Column(db.Integer)

class TREATMENT(db.Model, Export):
    __tablename__ = 'treatment'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.String(64))
    
class ATTACKS(db.Model, Export):
    __tablename__ = 'attacks'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3_1', 'q_3_2', 'q_3_3', 'q_3_4', 'q_4_1', 'q_4_2', 'q_4_3', 'q_4_4', 'q_4_5', 'q_4_6', 'q_5_1', 'q_5_2', 'q_5_3', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10_1', 'q_10_2', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15_1', 'q_15_2', 'q_16', 'q_17')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.String(64))
    q_3_1 = db.Column(db.String(64))
    q_3_2 = db.Column(db.String(64))
    q_3_3 = db.Column(db.Integer)
    q_3_4 = db.Column(db.Integer)
    q_4_1 = db.Column(db.String(64))
    q_4_2 = db.Column(db.String(64))
    q_4_3 = db.Column(db.Integer)
    q_4_4 = db.Column(db.Integer)
    q_4_5 = db.Column(db.Integer)
    q_4_6 = db.Column(db.Integer)
    q_5_1 = db.Column(db.String(64))
    q_5_2 = db.Column(db.String(64))
    q_5_3 = db.Column(db.Integer)
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.Integer)
    q_10_1 = db.Column(db.String(64))
    q_10_2 = db.Column(db.String(64))
    q_11 = db.Column(db.String(64))
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.String(64))
    q_15_1 = db.Column(db.Integer)
    q_15_2 = db.Column(db.Integer)
    q_16 = db.Column(db.String(64))
    q_17 = db.Column(db.Integer)
    
class COMMON_DIEASE(db.Model, Export):
    __tablename__ = 'common_diease'
    export_cols = ('p_id', 'status', 'q_1')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    
class SOMATOPATHY(db.Model, Export):
    __tablename__ = 'somatopathy'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.String(64))
    q_10 = db.Column(db.String(64))
    q_11 = db.Column(db.String(64))
    q_12 = db.Column(db.String(64))
    q_13 = db.Column(db.String(64))
    q_14 = db.Column(db.String(64))
    q_15 = db.Column(db.String(64))
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.String(64))

class LONGTERM_DIEASE(db.Model, Export):
    __tablename__ = 'longterm_diease'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))

class MENSE_PREGNACY(db.Model, Export):
    __tablename__ = 'mense_pregnacy'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.String(64))
    q_10 = db.Column(db.String(64))
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.String(64))
    q_13 = db.Column(db.String(64))
    q_14 = db.Column(db.String(64))
    q_15 = db.Column(db.String(64))
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)

class ABUSE(db.Model, Export):
    __tablename__ = 'abuse'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    
class FAMILY_HISTORY(db.Model, Export):
    __tablename__ = 'family_history'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    
class HAMA(db.Model, Export):
    __tablename__ = 'hama'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    
class PANNS(db.Model, Export):
    __tablename__ = 'panns'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21', 'q_22', 'q_23', 'q_24', 'q_25', 'q_26')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)
    q_15 = db.Column(db.Integer)
    q_16 = db.Column(db.Integer)
    q_17 = db.Column(db.Integer)
    q_18 = db.Column(db.Integer)
    q_19 = db.Column(db.Integer)
    q_20 = db.Column(db.Integer)
    q_21 = db.Column(db.Integer)
    q_22 = db.Column(db.Integer)
    q_23 = db.Column(db.Integer)
    q_24 = db.Column(db.Integer)
    q_25 = db.Column(db.Integer)
    q_26 = db.Column(db.Integer)
    
class MOAS(db.Model, Export):
    __tablename__ = 'moas'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    
class YBOCS(db.Model, Export):
    __tablename__ = 'ybocs'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.Integer)
    q_4 = db.Column(db.Integer)
    q_5 = db.Column(db.Integer)
    q_6 = db.Column(db.Integer)
    q_7 = db.Column(db.Integer)
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    
class GAF(db.Model, Export):
    __tablename__ = 'gaf'
    export_cols = ('p_id', 'status', 'q_1')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    
class TESS(db.Model, Export):
    __tablename__ = 'tess'
    export_cols = ('p_id', 'status', 'q_1_1', 'q_1_2', 'q_1_3', 'q_2_1', 'q_2_2', 'q_2_3', 'q_3_1', 'q_3_2', 'q_3_3', 'q_4_1', 'q_4_2', 'q_4_3', 'q_5_1', 'q_5_2', 'q_5_3', 'q_6_1', 'q_6_2', 'q_6_3', 'q_7_1', 'q_7_2', 'q_7_3', 'q_8_1', 'q_8_2', 'q_8_3', 'q_9_1', 'q_9_2', 'q_9_3', 'q_10_1', 'q_10_2', 'q_10_3', 'q_11_1', 'q_11_2', 'q_11_3', 'q_12_1', 'q_12_2', 'q_12_3', 'q_13_1', 'q_13_2', 'q_13_3', 'q_14_1', 'q_14_2', 'q_14_3', 'q_15_1', 'q_15_2', 'q_15_3', 'q_16_1', 'q_16_2', 'q_16_3', 'q_17_1', 'q_17_2', 'q_17_3', 'q_18_1', 'q_18_2', 'q_18_3', 'q_19_1', 'q_19_2', 'q_19_3', 'q_20_1', 'q_20_2', 'q_20_3', 'q_21_1', 'q_21_2', 'q_21_3', 'q_22_1', 'q_22_2', 'q_22_3', 'q_23_1', 'q_23_2', 'q_23_3', 'q_24_1', 'q_24_2', 'q_24_3', 'q_25_1', 'q_25_2', 'q_25_3', 'q_26_1', 'q_26_2', 'q_26_3', 'q_27_1', 'q_27_2', 'q_27_3', 'q_28_1', 'q_28_2', 'q_28_3', 'q_29_1', 'q_29_2', 'q_29_3', 'q_30_1', 'q_30_2', 'q_30_3', 'q_31_1', 'q_31_2', 'q_31_3', 'q_32_1', 'q_32_2', 'q_32_3', 'q_33_1', 'q_33_2', 'q_33_3', 'q_34_1', 'q_34_2', 'q_34_3')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1_1 = db.Column(db.Integer)
    q_1_2 = db.Column(db.Integer)
    q_1_3 = db.Column(db.Integer)
    q_2_1 = db.Column(db.Integer)
    q_2_2 = db.Column(db.Integer)
    q_2_3 = db.Column(db.Integer)
    q_3_1 = db.Column(db.Integer)
    q_3_2 = db.Column(db.Integer)
    q_3_3 = db.Column(db.Integer)
    q_4_1 = db.Column(db.Integer)
    q_4_2 = db.Column(db.Integer)
    q_4_3 = db.Column(db.Integer)
    q_5_1 = db.Column(db.Integer)
    q_5_2 = db.Column(db.Integer)
    q_5_3 = db.Column(db.Integer)
    q_6_1 = db.Column(db.Integer)
    q_6_2 = db.Column(db.Integer)
    q_6_3 = db.Column(db.Integer)
    q_7_1 = db.Column(db.Integer)
    q_7_2 = db.Column(db.Integer)
    q_7_3 = db.Column(db.Integer)
    q_8_1 = db.Column(db.Integer)
    q_8_2 = db.Column(db.Integer)
    q_8_3 = db.Column(db.Integer)
    q_9_1 = db.Column(db.Integer)
    q_9_2 = db.Column(db.Integer)
    q_9_3 = db.Column(db.Integer)
    q_10_1 = db.Column(db.Integer)
    q_10_2 = db.Column(db.Integer)
    q_10_3 = db.Column(db.Integer)
    q_11_1 = db.Column(db.Integer)
    q_11_2 = db.Column(db.Integer)
    q_11_3 = db.Column(db.Integer)
    q_12_1 = db.Column(db.Integer)
    q_12_2 = db.Column(db.Integer)
    q_12_3 = db.Column(db.Integer)
    q_13_1 = db.Column(db.Integer)
    q_13_2 = db.Column(db.Integer)
    q_13_3 = db.Column(db.Integer)
    q_14_1 = db.Column(db.Integer)
    q_14_2 = db.Column(db.Integer)
    q_14_3 = db.Column(db.Integer)
    q_15_1 = db.Column(db.Integer)
    q_15_2 = db.Column(db.Integer)
    q_15_3 = db.Column(db.Integer)
    q_16_1 = db.Column(db.Integer)
    q_16_2 = db.Column(db.Integer)
    q_16_3 = db.Column(db.Integer)
    q_17_1 = db.Column(db.Integer)
    q_17_2 = db.Column(db.Integer)
    q_17_3 = db.Column(db.Integer)
    q_18_1 = db.Column(db.Integer)
    q_18_2 = db.Column(db.Integer)
    q_18_3 = db.Column(db.Integer)
    q_19_1 = db.Column(db.Integer)
    q_19_2 = db.Column(db.Integer)
    q_19_3 = db.Column(db.Integer)
    q_20_1 = db.Column(db.Integer)
    q_20_2 = db.Column(db.Integer)
    q_20_3 = db.Column(db.Integer)
    q_21_1 = db.Column(db.Integer)
    q_21_2 = db.Column(db.Integer)
    q_21_3 = db.Column(db.Integer)
    q_22_1 = db.Column(db.Integer)
    q_22_2 = db.Column(db.Integer)
    q_22_3 = db.Column(db.Integer)
    q_23_1 = db.Column(db.Integer)
    q_23_2 = db.Column(db.Integer)
    q_23_3 = db.Column(db.Integer)
    q_24_1 = db.Column(db.Integer)
    q_24_2 = db.Column(db.Integer)
    q_24_3 = db.Column(db.Integer)
    q_25_1 = db.Column(db.Integer)
    q_25_2 = db.Column(db.Integer)
    q_25_3 = db.Column(db.Integer)
    q_26_1 = db.Column(db.Integer)
    q_26_2 = db.Column(db.Integer)
    q_26_3 = db.Column(db.Integer)
    q_27_1 = db.Column(db.Integer)
    q_27_2 = db.Column(db.Integer)
    q_27_3 = db.Column(db.Integer)
    q_28_1 = db.Column(db.Integer)
    q_28_2 = db.Column(db.Integer)
    q_28_3 = db.Column(db.Integer)
    q_29_1 = db.Column(db.Integer)
    q_29_2 = db.Column(db.Integer)
    q_29_3 = db.Column(db.Integer)
    q_30_1 = db.Column(db.Integer)
    q_30_2 = db.Column(db.Integer)
    q_30_3 = db.Column(db.Integer)
    q_31_1 = db.Column(db.Integer)
    q_31_2 = db.Column(db.Integer)
    q_31_3 = db.Column(db.Integer)
    q_32_1 = db.Column(db.Integer)
    q_32_2 = db.Column(db.Integer)
    q_32_3 = db.Column(db.Integer)
    q_33_1 = db.Column(db.Integer)
    q_33_2 = db.Column(db.Integer)
    q_33_3 = db.Column(db.Integer)
    q_34_1 = db.Column(db.Integer)
    q_34_2 = db.Column(db.Integer)
    q_34_3 = db.Column(db.Integer)
    
class TEST_EKG(db.Model, Export):
    __tablename__ = 'test_ekg'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.String(64))
    q_10 = db.Column(db.String(64))
    q_11 = db.Column(db.String(64))
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.String(64))
    
class TEST_BRS(db.Model, Export):
    __tablename__ = 'test_brs'
    export_cols = ('p_id', 'status', 'q_1', 'q_2_1', 'q_2_2', 'q_3_1', 'q_3_2', 'q_4_1', 'q_4_2', 'q_5_1', 'q_5_2', 'q_6_1', 'q_6_2', 'q_7_1', 'q_7_2', 'q_8_1', 'q_8_2', 'q_9_1', 'q_9_2', 'q_10_1', 'q_10_2', 'q_11_1', 'q_11_2', 'q_12_1', 'q_12_2', 'q_13_1', 'q_13_2', 'q_14_1', 'q_14_2', 'q_15_1', 'q_15_2', 'q_16_1', 'q_16_2', 'q_17_1', 'q_17_2', 'q_18_1', 'q_18_2', 'q_19_1', 'q_19_2', 'q_20_1', 'q_20_2', 'q_21_1', 'q_21_2', 'q_22_1', 'q_22_2')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2_1 = db.Column(db.String(64))
    q_2_2 = db.Column(db.Integer)
    q_3_1 = db.Column(db.String(64))
    q_3_2 = db.Column(db.Integer)
    q_4_1 = db.Column(db.String(64))
    q_4_2 = db.Column(db.Integer)
    q_5_1 = db.Column(db.String(64))
    q_5_2 = db.Column(db.Integer)
    q_6_1 = db.Column(db.String(64))
    q_6_2 = db.Column(db.Integer)
    q_7_1 = db.Column(db.String(64))
    q_7_2 = db.Column(db.Integer)
    q_8_1 = db.Column(db.String(64))
    q_8_2 = db.Column(db.Integer)
    q_9_1 = db.Column(db.String(64))
    q_9_2 = db.Column(db.Integer)
    q_10_1 = db.Column(db.String(64))
    q_10_2 = db.Column(db.Integer)
    q_11_1 = db.Column(db.String(64))
    q_11_2 = db.Column(db.Integer)
    q_12_1 = db.Column(db.String(64))
    q_12_2 = db.Column(db.Integer)
    q_13_1 = db.Column(db.String(64))
    q_13_2 = db.Column(db.Integer)
    q_14_1 = db.Column(db.String(64))
    q_14_2 = db.Column(db.Integer)
    q_15_1 = db.Column(db.String(64))
    q_15_2 = db.Column(db.Integer)
    q_16_1 = db.Column(db.String(64))
    q_16_2 = db.Column(db.Integer)
    q_17_1 = db.Column(db.String(64))
    q_17_2 = db.Column(db.Integer)
    q_18_1 = db.Column(db.String(64))
    q_18_2 = db.Column(db.Integer)
    q_19_1 = db.Column(db.String(64))
    q_19_2 = db.Column(db.Integer)
    q_20_1 = db.Column(db.String(64))
    q_20_2 = db.Column(db.Integer)
    q_21_1 = db.Column(db.String(64))
    q_21_2 = db.Column(db.Integer)
    q_22_1 = db.Column(db.String(64))
    q_22_2 = db.Column(db.Integer)
    
class TEST_BODS(db.Model, Export):
    __tablename__ = 'test_bods'
    export_cols = ('p_id', 'status', 'q_1', 'q_2_1', 'q_2_2', 'q_3_1', 'q_3_2', 'q_4_1', 'q_4_2', 'q_5_1', 'q_5_2', 'q_6_1', 'q_6_2', 'q_7_1', 'q_7_2', 'q_8_1', 'q_8_2', 'q_9_1', 'q_9_2', 'q_10_1', 'q_10_2', 'q_11_1', 'q_11_2', 'q_12_1', 'q_12_2', 'q_13_1', 'q_13_2', 'q_14_1', 'q_14_2', 'q_15_1', 'q_15_2', 'q_16_1', 'q_16_2', 'q_17_1', 'q_17_2', 'q_18_1', 'q_18_2', 'q_19_1', 'q_19_2', 'q_20_1', 'q_20_2', 'q_21_1', 'q_21_2', 'q_22_1', 'q_22_2', 'q_23_1', 'q_23_2', 'q_24_1', 'q_24_2', 'q_25_1', 'q_25_2', 'q_26_1', 'q_26_2', 'q_27_1', 'q_27_2', 'q_28_1', 'q_28_2', 'q_29_1', 'q_29_2', 'q_30_1', 'q_30_2', 'q_31_1', 'q_31_2', 'q_32_1', 'q_32_2', 'q_33_1', 'q_33_2', 'q_34_1', 'q_34_2', 'q_35_1', 'q_35_2', 'q_36_1', 'q_36_2', 'q_37_1', 'q_37_2', 'q_38_1', 'q_38_2', 'q_39_1', 'q_39_2', 'q_40_1', 'q_40_2', 'q_41_1', 'q_41_2', 'q_42_1', 'q_42_2', 'q_43_1', 'q_43_2')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2_1 = db.Column(db.String(64))
    q_2_2 = db.Column(db.Integer)
    q_3_1 = db.Column(db.String(64))
    q_3_2 = db.Column(db.Integer)
    q_4_1 = db.Column(db.String(64))
    q_4_2 = db.Column(db.Integer)
    q_5_1 = db.Column(db.String(64))
    q_5_2 = db.Column(db.Integer)
    q_6_1 = db.Column(db.String(64))
    q_6_2 = db.Column(db.Integer)
    q_7_1 = db.Column(db.String(64))
    q_7_2 = db.Column(db.Integer)
    q_8_1 = db.Column(db.String(64))
    q_8_2 = db.Column(db.Integer)
    q_9_1 = db.Column(db.String(64))
    q_9_2 = db.Column(db.Integer)
    q_10_1 = db.Column(db.String(64))
    q_10_2 = db.Column(db.Integer)
    q_11_1 = db.Column(db.String(64))
    q_11_2 = db.Column(db.Integer)
    q_12_1 = db.Column(db.String(64))
    q_12_2 = db.Column(db.Integer)
    q_13_1 = db.Column(db.String(64))
    q_13_2 = db.Column(db.Integer)
    q_14_1 = db.Column(db.String(64))
    q_14_2 = db.Column(db.Integer)
    q_15_1 = db.Column(db.String(64))
    q_15_2 = db.Column(db.Integer)
    q_16_1 = db.Column(db.String(64))
    q_16_2 = db.Column(db.Integer)
    q_17_1 = db.Column(db.String(64))
    q_17_2 = db.Column(db.Integer)
    q_18_1 = db.Column(db.String(64))
    q_18_2 = db.Column(db.Integer)
    q_19_1 = db.Column(db.String(64))
    q_19_2 = db.Column(db.Integer)
    q_20_1 = db.Column(db.String(64))
    q_20_2 = db.Column(db.Integer)
    q_21_1 = db.Column(db.String(64))
    q_21_2 = db.Column(db.Integer)
    q_22_1 = db.Column(db.String(64))
    q_22_2 = db.Column(db.Integer)
    q_23_1 = db.Column(db.String(64))
    q_23_2 = db.Column(db.Integer)
    q_24_1 = db.Column(db.String(64))
    q_24_2 = db.Column(db.Integer)
    q_25_1 = db.Column(db.String(64))
    q_25_2 = db.Column(db.Integer)
    q_26_1 = db.Column(db.String(64))
    q_26_2 = db.Column(db.Integer)
    q_27_1 = db.Column(db.String(64))
    q_27_2 = db.Column(db.Integer)
    q_28_1 = db.Column(db.String(64))
    q_28_2 = db.Column(db.Integer)
    q_29_1 = db.Column(db.String(64))
    q_29_2 = db.Column(db.Integer)
    q_30_1 = db.Column(db.String(64))
    q_30_2 = db.Column(db.Integer)
    q_31_1 = db.Column(db.String(64))
    q_31_2 = db.Column(db.Integer)
    q_32_1 = db.Column(db.String(64))
    q_32_2 = db.Column(db.Integer)
    q_33_1 = db.Column(db.String(64))
    q_33_2 = db.Column(db.Integer)
    q_34_1 = db.Column(db.String(64))
    q_34_2 = db.Column(db.Integer)
    q_35_1 = db.Column(db.String(64))
    q_35_2 = db.Column(db.Integer)
    q_36_1 = db.Column(db.String(64))
    q_36_2 = db.Column(db.Integer)
    q_37_1 = db.Column(db.String(64))
    q_37_2 = db.Column(db.Integer)
    q_38_1 = db.Column(db.String(64))
    q_38_2 = db.Column(db.Integer)
    q_39_1 = db.Column(db.String(64))
    q_39_2 = db.Column(db.Integer)
    q_40_1 = db.Column(db.String(64))
    q_40_2 = db.Column(db.Integer)
    q_41_1 = db.Column(db.String(64))
    q_41_2 = db.Column(db.Integer)
    q_42_1 = db.Column(db.String(64))
    q_42_2 = db.Column(db.Integer)
    q_43_1 = db.Column(db.String(64))
    q_43_2 = db.Column(db.Integer)
    
class TEST_BFS(db.Model, Export):
    __tablename__ = 'test_bfs'
    export_cols = ('p_id', 'status', 'q_1', 'q_2_1', 'q_2_2', 'q_3_1', 'q_3_2', 'q_4_1', 'q_4_2', 'q_5_1', 'q_5_2', 'q_6_1', 'q_6_2', 'q_7_1', 'q_7_2', 'q_8_1', 'q_8_2', 'q_9_1', 'q_9_2', 'q_10_1', 'q_10_2', 'q_11_1', 'q_11_2', 'q_12_1', 'q_12_2', 'q_13_1', 'q_13_2', 'q_14_1', 'q_14_2', 'q_15_1', 'q_15_2', 'q_16_1', 'q_16_2')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2_1 = db.Column(db.String(64))
    q_2_2 = db.Column(db.Integer)
    q_3_1 = db.Column(db.String(64))
    q_3_2 = db.Column(db.Integer)
    q_4_1 = db.Column(db.String(64))
    q_4_2 = db.Column(db.Integer)
    q_5_1 = db.Column(db.String(64))
    q_5_2 = db.Column(db.Integer)
    q_6_1 = db.Column(db.String(64))
    q_6_2 = db.Column(db.Integer)
    q_7_1 = db.Column(db.String(64))
    q_7_2 = db.Column(db.Integer)
    q_8_1 = db.Column(db.String(64))
    q_8_2 = db.Column(db.Integer)
    q_9_1 = db.Column(db.String(64))
    q_9_2 = db.Column(db.Integer)
    q_10_1 = db.Column(db.String(64))
    q_10_2 = db.Column(db.Integer)
    q_11_1 = db.Column(db.String(64))
    q_11_2 = db.Column(db.Integer)
    q_12_1 = db.Column(db.String(64))
    q_12_2 = db.Column(db.Integer)
    q_13_1 = db.Column(db.String(64))
    q_13_2 = db.Column(db.Integer)
    q_14_1 = db.Column(db.String(64))
    q_14_2 = db.Column(db.Integer)
    q_15_1 = db.Column(db.String(64))
    q_15_2 = db.Column(db.Integer)
    q_16_1 = db.Column(db.String(64))
    q_16_2 = db.Column(db.Integer)
    
class TEST_IMMS(db.Model, Export):
    __tablename__ = 'test_imms'
    export_cols = ('p_id', 'status', 'q_1', 'q_2_1', 'q_2_2', 'q_3_1', 'q_3_2', 'q_4_1', 'q_4_2', 'q_5_1', 'q_5_2', 'q_6_1', 'q_6_2', 'q_7_1', 'q_7_2', 'q_8_1', 'q_8_2', 'q_9_1', 'q_9_2', 'q_10_1', 'q_10_2', 'q_11_1', 'q_11_2', 'q_12_1', 'q_12_2', 'q_13_1', 'q_13_2', 'q_14_1', 'q_14_2', 'q_15_1', 'q_15_2', 'q_16_1', 'q_16_2', 'q_17_1', 'q_17_2')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2_1 = db.Column(db.String(64))
    q_2_2 = db.Column(db.Integer)
    q_3_1 = db.Column(db.String(64))
    q_3_2 = db.Column(db.Integer)
    q_4_1 = db.Column(db.String(64))
    q_4_2 = db.Column(db.Integer)
    q_5_1 = db.Column(db.String(64))
    q_5_2 = db.Column(db.Integer)
    q_6_1 = db.Column(db.String(64))
    q_6_2 = db.Column(db.Integer)
    q_7_1 = db.Column(db.String(64))
    q_7_2 = db.Column(db.Integer)
    q_8_1 = db.Column(db.String(64))
    q_8_2 = db.Column(db.Integer)
    q_9_1 = db.Column(db.String(64))
    q_9_2 = db.Column(db.Integer)
    q_10_1 = db.Column(db.String(64))
    q_10_2 = db.Column(db.Integer)
    q_11_1 = db.Column(db.String(64))
    q_11_2 = db.Column(db.Integer)
    q_12_1 = db.Column(db.String(64))
    q_12_2 = db.Column(db.Integer)
    q_13_1 = db.Column(db.String(64))
    q_13_2 = db.Column(db.Integer)
    q_14_1 = db.Column(db.String(64))
    q_14_2 = db.Column(db.Integer)
    q_15_1 = db.Column(db.String(64))
    q_15_2 = db.Column(db.Integer)
    q_16_1 = db.Column(db.String(64))
    q_16_2 = db.Column(db.Integer)
    q_17_1 = db.Column(db.String(64))
    q_17_2 = db.Column(db.Integer)
    
class TEST_DRUG(db.Model, Export):
    __tablename__ = 'test_drug'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    
class TEST_TM(db.Model, Export):
    __tablename__ = 'test_tm'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))

class TEST_HEMODYNAMIC(db.Model, Export):
    __tablename__ = 'test_hemodynamic'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19', 'q_20', 'q_21', 'q_22', 'q_23', 'q_24', 'q_25', 'q_26', 'q_27', 'q_28', 'q_29', 'q_30', 'q_31', 'q_32')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.String(64))
    q_10 = db.Column(db.String(64))
    q_11 = db.Column(db.String(64))
    q_12 = db.Column(db.String(64))
    q_13 = db.Column(db.String(64))
    q_14 = db.Column(db.String(64))
    q_15 = db.Column(db.String(64))
    q_16 = db.Column(db.String(64))
    q_17 = db.Column(db.String(64))
    q_18 = db.Column(db.String(64))
    q_19 = db.Column(db.String(64))
    q_20 = db.Column(db.String(64))
    q_21 = db.Column(db.String(64))
    q_22 = db.Column(db.String(64))
    q_23 = db.Column(db.String(64))
    q_24 = db.Column(db.String(64))
    q_25 = db.Column(db.String(64))
    q_26 = db.Column(db.String(64))
    q_27 = db.Column(db.String(64))
    q_28 = db.Column(db.String(64))
    q_29 = db.Column(db.String(64))
    q_30 = db.Column(db.String(64))
    q_31 = db.Column(db.String(64))
    q_32 = db.Column(db.String(64))
    
class TEST_SUPERSONIC(db.Model, Export):
    __tablename__ = 'test_supersonic'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    
class TEST_BMD(db.Model, Export):
    __tablename__ = 'test_bmd'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    
class TEST_SSEP(db.Model, Export):
    __tablename__ = 'test_ssep'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    
class TEST_BAEP(db.Model, Export):
    __tablename__ = 'test_baep'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    
class TEST_VEP_PRE(db.Model, Export):
    __tablename__ = 'test_vep_pre'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    
class TEST_REP(db.Model, Export):
    __tablename__ = 'test_rep'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    
class TEST_CNV(db.Model, Export):
    __tablename__ = 'test_cnv'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.Integer)
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.String(64))
    
class TEST_EMT(db.Model, Export):
    __tablename__ = 'test_emt'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    
class TEST_WM(db.Model, Export):
    __tablename__ = 'test_wm'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.String(64))
    q_10 = db.Column(db.String(64))
    q_11 = db.Column(db.String(64))
    q_12 = db.Column(db.String(64))
    q_13 = db.Column(db.String(64))
    q_14 = db.Column(db.String(64))
    q_15 = db.Column(db.String(64))
    
class TEST_WAIS_RC(db.Model, Export):
    __tablename__ = 'test_wais_rc'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    
class TEST_WCST(db.Model, Export):
    __tablename__ = 'test_wcst'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14', 'q_15', 'q_16', 'q_17', 'q_18', 'q_19')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.String(64))
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.String(64))
    q_9 = db.Column(db.String(64))
    q_10 = db.Column(db.String(64))
    q_11 = db.Column(db.String(64))
    q_12 = db.Column(db.String(64))
    q_13 = db.Column(db.String(64))
    q_14 = db.Column(db.String(64))
    q_15 = db.Column(db.String(64))
    q_16 = db.Column(db.String(64))
    q_17 = db.Column(db.String(64))
    q_18 = db.Column(db.String(64))
    q_19 = db.Column(db.String(64))
    
class SAE(db.Model, Export):
    __tablename__ = 'sae'
    export_cols = ('p_id', 'status', 'q_1', 'q_2', 'q_3', 'q_4', 'q_5', 'q_6', 'q_7', 'q_8', 'q_9', 'q_10', 'q_11', 'q_12', 'q_13', 'q_14')
    id = db.Column(db.Integer, primary_key=True)
    p_id = db.Column(db.Integer, db.ForeignKey('patient_infos.id'))
    status = db.Column(db.String(16), db.ForeignKey('follow_ups.q_1'))
    q_1 = db.Column(db.Integer)
    q_2 = db.Column(db.String(64))
    q_3 = db.Column(db.String(64))
    q_4 = db.Column(db.String(64))
    q_5 = db.Column(db.String(64))
    q_6 = db.Column(db.String(64))
    q_7 = db.Column(db.String(64))
    q_8 = db.Column(db.Integer)
    q_9 = db.Column(db.Integer)
    q_10 = db.Column(db.Integer)
    q_11 = db.Column(db.Integer)
    q_12 = db.Column(db.Integer)
    q_13 = db.Column(db.Integer)
    q_14 = db.Column(db.Integer)